/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BusinessSectorsRouteImport } from './routes/business-sectors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessSectorsIndexRouteImport } from './routes/business-sectors.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as BusinessSectorsSlugRouteImport } from './routes/business-sectors.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSectorsRoute = BusinessSectorsRouteImport.update({
  id: '/business-sectors',
  path: '/business-sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSectorsIndexRoute = BusinessSectorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessSectorsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const BusinessSectorsSlugRoute = BusinessSectorsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BusinessSectorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-sectors': typeof BusinessSectorsRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/business-sectors/$slug': typeof BusinessSectorsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/business-sectors/': typeof BusinessSectorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/business-sectors/$slug': typeof BusinessSectorsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/business-sectors': typeof BusinessSectorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-sectors': typeof BusinessSectorsRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/business-sectors/$slug': typeof BusinessSectorsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/business-sectors/': typeof BusinessSectorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business-sectors'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/projects'
    | '/sitemap.xml'
    | '/business-sectors/$slug'
    | '/projects/$slug'
    | '/business-sectors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/projects'
    | '/sitemap.xml'
    | '/business-sectors/$slug'
    | '/projects/$slug'
    | '/business-sectors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business-sectors'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/projects'
    | '/sitemap.xml'
    | '/business-sectors/$slug'
    | '/projects/$slug'
    | '/business-sectors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessSectorsRoute: typeof BusinessSectorsRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-sectors': {
      id: '/business-sectors'
      path: '/business-sectors'
      fullPath: '/business-sectors'
      preLoaderRoute: typeof BusinessSectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-sectors/': {
      id: '/business-sectors/'
      path: '/'
      fullPath: '/business-sectors/'
      preLoaderRoute: typeof BusinessSectorsIndexRouteImport
      parentRoute: typeof BusinessSectorsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/business-sectors/$slug': {
      id: '/business-sectors/$slug'
      path: '/$slug'
      fullPath: '/business-sectors/$slug'
      preLoaderRoute: typeof BusinessSectorsSlugRouteImport
      parentRoute: typeof BusinessSectorsRoute
    }
  }
}

interface BusinessSectorsRouteChildren {
  BusinessSectorsSlugRoute: typeof BusinessSectorsSlugRoute
  BusinessSectorsIndexRoute: typeof BusinessSectorsIndexRoute
}

const BusinessSectorsRouteChildren: BusinessSectorsRouteChildren = {
  BusinessSectorsSlugRoute: BusinessSectorsSlugRoute,
  BusinessSectorsIndexRoute: BusinessSectorsIndexRoute,
}

const BusinessSectorsRouteWithChildren = BusinessSectorsRoute._addFileChildren(
  BusinessSectorsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessSectorsRoute: BusinessSectorsRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
